{% set name = "fury" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc7bdbdf1632f317f40c717c2f34a6b8424ce5abda3ebda31a058c0b725a316a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - vtk
    - matplotlib-base
    - six

test:
  imports:
    - fury

about:
  home: http://github.com/fury-gl/fury
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Free Unified Rendering for Python - Scientific Visualization
  description: |
    Free Unified Rendering for Python (FURY) is a library that offers
    a collection of new widgets, functionnality to vtk. It works under
    Python 2.7 and Python 3.4+
  doc_url: http://fury.gl/
  dev_url: https://github.com/fury-gl/fury

extra:
  recipe-maintainers:
    - skoudoro
    - garyfallidis
