{% set name = "fury" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a55eae00a949304156c75fe26b6e0130c5d7b172593ea626399b8b9eda5c78c7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
    - setuptools_scm

  run:
    - python >=3.8
    - numpy
    - scipy
    - vtk
    - matplotlib-base
    - six

test:
  imports:
    - fury

about:
  home: http://github.com/fury-gl/fury
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Free Unified Rendering for Python - Scientific Visualization
  description: |
    Free Unified Rendering for Python (FURY) is a library that offers
    a collection of new widgets, functionnality to vtk. It works under
    Python 2.7 and Python 3.4+
  doc_url: http://fury.gl/
  dev_url: https://github.com/fury-gl/fury

extra:
  recipe-maintainers:
    - skoudoro
    - garyfallidis
