travis:
  secure:
    BINSTAR_TOKEN: pEbNA5ZJZEbRB6of7RPkiuGCgur/VXCraTEq5SnWkRiuPQioyCKwu9+tGvVTq5Og3cc7Wz4yk/oSYVY6Z14nOCmQWu+qcynM4iLO3KU1DlxGYGxLqKIQFdtJdxFmghGuvP8DsVu7q+cnJnDSOQYd0HO8CxesQIDwWgeeKNNc32LWxfNltdAkQYzKrF3r7xzCr99z5pE3PMHHziK0/k0ODSc1FoCYNz6VNUs8SxHb+TvsyFIUL6ZRvu8Cw7di9NkuTF/Y46u7+H2j7YRGJ3qVnwD7Ffidv0bvhZDp3EjSkIDxc8TCu7UJfp+2IndIjiVXaw72R/55d20llsub/5CCJO9/OOSv0JbbaiuhJlP1ov7zEwq7wkEK5XXuaDxQlb4x1GXbwxSjso4EcZyUivP7/fLcMpMgKPGsQr2jZWkxEoWRPFUQivKk6qKPpMWJLPsPNvGAbwFy04+E9G3xu3QkE02tG2EYb6zQfRS0cq3oKQ82E9Z4hwrn224OlRH5oYAvfQj4TmC+v+1khgH6XBpZcGWC+TTCNm7HPewzIw7AdngpDsPtK/mN8jZiEs64kFdQdVtiSl55Aq/+IwncmFZ0/F4rT9y907e4u+UPmKgCsW/OA45o2FjTmex8epuzwsAdMlnbfcIWbTdni+S/loK72fpHgnUw8gxVzZh3KF0OJLY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
